### ISSUE TITLE
Setting the control_method for a zone

### ISSUE THREAD

**Issue by nagelm** [TheNoctambulist/hass-airtouch#7]
### Checklist

- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/thenoctambulist/hass-airtouch/issues?q=is%3Aissue+label%3A%22feature-request%22+).
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).

### Proposal

I would like a way to create an automation which sets the control_method for a zone back to 'temperature' if it has been left as 'damper' for x period. Ideally, I would like to do this without knowing or changing the temperature of the zone.

I am fairly early in my HA journey so forgive me if this function already exists.

**Comment by TheNoctambulist** [comment]
I haven't added a specific service call for changing the control method, but you could just call the `climate.set_temperature` service using the current target temperature, for example:
```
service: climate.set_temperature
metadata: {}
data:
  temperature: "{{ state_attr(\"climate.my_zone\", \"temperature\") }}"
target:
  entity_id: climate.my_zone
```
